### ISSUE TITLE
Documents doubts and improvements requests

### ISSUE THREAD

**Issue by yangricardo** [mohrazzak/better-nestjs-zod-prisma#2]
Hi, 
First, thanks for the initiative, i also have used the old nestjs-zod and had no idea it were fully discontinued.

Does your generator uses the same structure than `nest-zod-prisma` ? 
Would be nice to have it better described on how to use it

**Comment by mohrazzak** [comment]
Hi, I am very sorry I didn't see your Issue
Yes,It uses the same generator but I have applied some improvements described in the docs such as nullable and nullish, and repeated Enum import in schemas and so on 
I actually would love to write a good description but I really don't have a lot of time for now, So I would appreciate any PR 
If you needed any more information about the package you can reach me in a discord call and I would love to explain what is foggy for you so you can PR here.
appreciate it!
@yangricardo 
@timseriakov

**Comment by mohrazzak** [comment]
Tho I think it is more clear with this changes I made to the README 
Please check that so I can close this
