### ISSUE TITLE
how to use your lib

### ISSUE THREAD

**Issue by timseriakov** [mohrazzak/better-nestjs-zod-prisma#3]
Hey man, tell us how to use your lib please?

**Comment by timseriakov** [comment]
I got it. 

So after `npm i better-nestjs-zod-prisma` need to specify 

`provider = "nestjs-zod-prisma"` not `better-nestjs-zod-prisma`

That's a little counterintuitive.

**Comment by mohrazzak** [comment]
Thank you for this.
